chore: prettier rules and next core web vitals linting added to .eslintrc
valory-xyz/autonolas-frontend-mono pull request #107
Opened 2024-09-30 11:07 UTC by atepem

## Proposed changes

Added overall linter using next/core-web-vitals and prettier rules that fixes formatting on save (same settings applied on olas website). All apps and files have been fixed using ```yarn nx lint --fix [appname]```.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-09-30 13:31 UTC, truemiller approved these changes

2024-10-01 08:33 UTC, Tanya-atatakai requested changes

2024-10-01 08:33 UTC, Tanya-atatakai commented on .eslintrc.json
> +    "prettier/prettier": ["error", {
we have a prettier file close to the eslint.json 
`.prettierrc`, can you please move all the settings from it here and remove that file?

2024-10-01 11:56 UTC, Tanya-atatakai approved these changes

2024-10-01 12:21 UTC, merged