feat: launch app init
valory-xyz/autonolas-frontend-mono pull request #36
Opened 2024-06-13 18:45 UTC by mohandast52

## Proposed changes

- Network switch feature
- Wallet connect integration
- Empty contract list view

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-06-17 09:08 UTC, truemiller commented on apps/launch/common-util/constants/urls.ts
> +  myStackingContract: 'my-staking-contracts',
```suggestion
  myStakingContract: 'my-staking-contracts',
```
likely need to refactor where it's imported too :/

2024-06-17 10:43 UTC, Tanya-atatakai requested changes

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/common-util/config/supportedChains.tsx
> +    vmType: VM_TYPE.EVM,
maybe won't need this as we're not going to support Solana in this app

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/common-util/config/wagmi.ts
> +export const SUPPORTED_CHAINS: [Chain, ...Chain[]] = [
shouldn't we have the same list of chains in the `apps/launch/common-util/config/supportedChains.tsx` as in here? it's confusing that they are different

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/common-util/config/wagmi.ts
> +    // TODO: merge two sources of RPCs into one?
honestly, I don't remember what I meant by this comment :D

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/common-util/constants/urls.ts
> +export const EXPLORE_URLS: Record<string, string> = {
do you think it makes sense to move it to the `libs/util-constants`?

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/common-util/constants/urls.ts
> +export const GET_VEOLAS_URL = 'https://member.olas.network/';
don't think we'll need it here, can we remove?

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/common-util/functions/addresses.ts
> +export const truncateAddress = (address: Address | string) =>
does it make sense to move it to the `libs/util-functions`?

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/common-util/functions/frontend-library.ts
> +export const CHAIN_NAMES: Record<string, string> = {
maybe we can move this to the `libs/util-constants`

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/common-util/functions/web3.ts
> +export const getVeOlasContract = () => {
highly likely won't be needed, can we remove?

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/common-util/hooks/useNetworkHelpers.tsx
> +export const useGetChainIdFromPath = (networkName: string | undefined) => {
I only see this function used in the app, but don't see all the rest exported, e.g. `useNetworkHelpers`, `useIsValidNetworkName`, etc. do you think we can remove them?

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/components/Layout/SwitchNetworkSelect/SwitchNetworkSelect.tsx
> +        disabled={PAGES_TO_LOAD_WITHOUT_CHAINID.some((e) => path.includes(e))}
would that be easier to check `PAGES_TO_LOAD_**WITH**_CHAINID` instead? `page-not-found` doesn't support chainId, `paths` won't support it

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/components/Layout/SwitchNetworkSelect/SwitchNetworkSelect.tsx
> +        options={ALL_SUPPORTED_CHAINS.map((e) => ({
can we do this mapping outside of the component so it won't be recalculated on each re-render?

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/components/Layout/SwitchNetworkSelect/SwitchNetworkSelect.tsx
> +          if (PAGES_TO_LOAD_WITHOUT_CHAINID.find((e) => e === path)) {
same question here - would that be easier to check pages **with** chainId (there's only one or maybe two if we decide to use the same patter for a contract page)

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/components/Layout/SwitchNetworkSelect/useHandleRoute.tsx
> +const isValidNetworkName = (name?: string) => {
seems that we have the same function in `apps/launch/common-util/hooks/useNetworkHelpers.tsx`

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/components/Layout/SwitchNetworkSelect/useHandleRoute.tsx
> +    // if already on my-staking-contracts or proposals page then no need to redirect
can we update the comment here, it doesn't make sense to mention proposals here

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/components/Layout/SwitchNetworkSelect/useHandleRoute.tsx
> +     * - if user navigates to `/ethereum` then redirect to `/ethereum/my-stack-contracts` page
maybe worths using `URL.myStackingContract` instead if it's value, in the comments we have here `my-stack-contracts` but in the line 85 `my-stacking-contracts` - a bit confusing

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/components/MyStakingContracts/MyStakingContracts.tsx
> +        {match(isAccountConnected)
interesting

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/components/MyStakingContracts/MyStakingContracts.tsx
> +    <>
Can we reduce width here, to ~1000px as in Figma?
I used this for the Contract page on Govern, if that suits

```
const StyledMain = styled.main`
  display: flex;
  flex-direction: column;
  max-width: 800px;
  margin: 0 auto;
`;
```

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/components/MyStakingContracts/MyStakingContracts.tsx
> +          My staking contracts on Gnosis
can be selected chain instead of hardcoded Gnosis?

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/types/Address.ts
> +export type Address = `0x${string}`;
as Josh suggested we can import Address from viem, can remove this I guess

2024-06-17 10:43 UTC, Tanya-atatakai commented on apps/launch/types/index.ts
> +export type * from './Allocation';
I suggest we remove all types from here, they are all related to the Govern app

2024-06-17 10:43 UTC, Tanya-atatakai commented on libs/util-prohibited-data/src/index.ts
> +export const isAddressProhibited = (address: Address | undefined) => {
does it make sense to move this function right to the `libs/util-prohibited-data`?

2024-06-17 12:28 UTC, Tanya-atatakai commented on apps/launch/components/Layout/SwitchNetworkSelect/SwitchNetworkSelect.tsx
can we rename this file to just index? `apps/launch/components/Layout/SwitchNetworkSelect/SwitchNetworkSelect.tsx` -> `apps/launch/components/Layout/SwitchNetworkSelect/index.tsx`

2024-06-17 12:28 UTC, Tanya-atatakai commented on apps/launch/components/MyStakingContracts/MyStakingContracts.tsx
Can we rename this file to index?
`apps/launch/components/MyStakingContracts/MyStakingContracts.tsx` -> `apps/launch/components/MyStakingContracts/index.tsx` - easier to import + consistency with other components

2024-06-17 12:37 UTC, Tanya-atatakai commented on apps/launch/pages/[network]/my-staking-contracts.tsx
can we follow the same pattern with hierarchy as in registry? instead of`pages/[network]/my-staking-contracts.tsx` can we have e.g. `pages/[network]/contracts/index.tsx` (or `pages/[network]/my-contracts/index.tsx` so we can then add `pages/[network]/contracts/[id]` and `pages/[network]/contracts/create.tsx`  

<img width="246" alt="image" src="https://github.com/valory-xyz/autonolas-frontend-mono/assets/22725775/7382727a-3d80-45fb-a2cf-eb9c673f9eb8">

2024-06-18 12:10 UTC, oaksprout approved these changes

2024-06-18 12:18 UTC, truemiller approved these changes

2024-06-18 12:21 UTC, merged