(registry) fix: multisig fix in service details
valory-xyz/autonolas-frontend-mono pull request #89
Opened 2024-08-28 09:03 UTC by mohandast52

## Types of changes
- The `multisig` functionality in the service should work as expected.
- It has been tested with Gnosis Safe and MetaMask, as demonstrated in the video below.

<hr />

- Metamask test with Arbitrum Sepolia

https://github.com/user-attachments/assets/95db07cd-59d9-4d13-8181-e27c5e1e6334

- Safe test with Gnosis Chiado

https://github.com/user-attachments/assets/ef31d8f8-5d42-4ce9-bc31-c78ca212f9c2

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-08-28 16:03 UTC, truemiller commented on package.json
> +    "ethers-v5": "npm:ethers@5.7.2",
🧠 never saw this before, nice!

2024-08-28 16:03 UTC, truemiller approved these changes

2024-08-29 09:02 UTC, Tanya-atatakai requested changes

2024-08-29 09:04 UTC, Tanya-atatakai commented on apps/autonolas-registry/components/ListServices/ServiceState/3rdStepFinishedRegistration/utils.jsx
> + * How to test `onMultisigSubmit` function (step 3 in service)
wonder, maybe it's because that I used fork? 🤔

2024-08-29 10:23 UTC, kupermind commented on apps/autonolas-registry/components/ListServices/ServiceState/3rdStepFinishedRegistration/utils.jsx
> +      const packedData = ethers.utils.solidityPack(['address', 'bytes'], [multisig, safeExecData]);
So, this is back to using ethers v5 as I understand from the header.

2024-08-29 11:07 UTC, Tanya-atatakai commented on apps/autonolas-registry/components/ListServices/ServiceState/3rdStepFinishedRegistration/utils.jsx
> + * How to test `onMultisigSubmit` function (step 3 in service)
I didn't disable, I removed isDisabled to unblock the button :DDD okay, will try testing on testnet

2024-08-29 11:43 UTC, kupermind approved these changes

2024-08-29 11:50 UTC, Tanya-atatakai approved these changes

2024-08-29 19:01 UTC, merged